# Generated by Django 3.2.9 on 2021-11-19 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Geolocations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=40)),
                ('country', models.CharField(max_length=40)),
                ('latitude', models.FloatField()),
                ('longitude', models.CharField(max_length=30)),
                ('duration', models.CharField(max_length=40)),
            ],
            options={
                'verbose_name_plural': 'Geolocations',
            },
        ),
    ]
