# Generated by Django 3.2.9 on 2021-11-19 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_geolocations_place'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geolocations',
            name='longitude',
            field=models.FloatField(),
        ),
    ]
